#include <map>
#include "bimap.h"
// Instruction and their valid addressing modes
static const map<string, vector<AddressMode>> instruction_to_token_types =
{
    // Load/Store Operations
    {"LDA", {IMMEDIATE, ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE, Y_ABSOLUTE, X_INDEX_ZP_INDIRECT, ZP_INDIRECT_Y_INDEX}},
    {"LDX", {IMMEDIATE, ZERO_PAGE, Y_ZERO_PAGE, ABSOLUTE, Y_ABSOLUTE}},
    {"LDY", {IMMEDIATE, ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE}},
    {"STA", {ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE, Y_ABSOLUTE, X_INDEX_ZP_INDIRECT, ZP_INDIRECT_Y_INDEX}},
    {"STX", {ZERO_PAGE, Y_ZERO_PAGE, ABSOLUTE}},
    {"STY", {ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE}},

    // Register Transfers
    {"TAX", {IMPLIED}},
    {"TAY", {IMPLIED}},
    {"TXA", {IMPLIED}},
    {"TYA", {IMPLIED}},

    // Stack Operations
    {"TSX", {IMPLIED}},
    {"TXS", {IMPLIED}},
    {"PHA", {IMPLIED}},
    {"PHP", {IMPLIED}},
    {"PLA", {IMPLIED}},
    {"PLP", {IMPLIED}},

    // Logical
    {"AND", {IMMEDIATE, ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE, Y_ABSOLUTE, X_INDEX_ZP_INDIRECT, ZP_INDIRECT_Y_INDEX}},
    {"EOR", {IMMEDIATE, ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE, Y_ABSOLUTE, X_INDEX_ZP_INDIRECT, ZP_INDIRECT_Y_INDEX}},
    {"ORA", {IMMEDIATE, ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE, Y_ABSOLUTE, X_INDEX_ZP_INDIRECT, ZP_INDIRECT_Y_INDEX}},
    {"BIT", {ZERO_PAGE, ABSOLUTE}},

    // Arithmetic
    {"ADC", {IMMEDIATE, ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE, Y_ABSOLUTE, X_INDEX_ZP_INDIRECT, ZP_INDIRECT_Y_INDEX}},
    {"SBC", {IMMEDIATE, ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE, Y_ABSOLUTE, X_INDEX_ZP_INDIRECT, ZP_INDIRECT_Y_INDEX}},
    {"CMP", {IMMEDIATE, ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE, Y_ABSOLUTE, X_INDEX_ZP_INDIRECT, ZP_INDIRECT_Y_INDEX}},
    {"CPX", {IMMEDIATE, ZERO_PAGE, ABSOLUTE}},
    {"CPY", {IMMEDIATE, ZERO_PAGE, ABSOLUTE}},

    // Increments & Decrements
    {"INC", {ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE}},
    {"INX", {IMPLIED}},
    {"INY", {IMPLIED}},
    {"DEC", {ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE}},
    {"DEX", {IMPLIED}},
    {"DEY", {IMPLIED}},

    // Shifts
    {"ASL", {ACCUMULATOR, ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE}},
    {"LSR", {ACCUMULATOR, ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE}},
    {"ROL", {ACCUMULATOR, ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE}},
    {"ROR", {ACCUMULATOR, ZERO_PAGE, X_ZERO_PAGE, ABSOLUTE, X_ABSOLUTE}},

    // Jumps & Calls
    {"JMP", {ABSOLUTE, ABS_INDIRECT}},
    {"JSR", {ABSOLUTE}},
    {"RTS", {IMPLIED}},

    // Branches
    {"BCC", {RELATIVE}},
    {"BCS", {RELATIVE}},
    {"BEQ", {RELATIVE}},
    {"BMI", {RELATIVE}},
    {"BNE", {RELATIVE}},
    {"BPL", {RELATIVE}},
    {"BVC", {RELATIVE}},
    {"BVS", {RELATIVE}},

    // Status Flag Changes
    {"CLC", {IMPLIED}},
    {"CLD", {IMPLIED}},
    {"CLI", {IMPLIED}},
    {"CLV", {IMPLIED}},
    {"SEC", {IMPLIED}},
    {"SED", {IMPLIED}},
    {"SEI", {IMPLIED}},

    // System Functions
    {"BRK", {IMPLIED}},
    {"NOP", {IMPLIED}},
    {"RTI", {IMPLIED}},
};

inline const auto& instruction_opcode_bimap = construct_bimap();